### PR TITLE
Comment out test ImageCarousel from ProductPage

### PR DESCRIPTION
**Pull request by fromITzerotoIThero**
I commented out test ImageCarousel and excessive product description - it caused half of `ProductPage` to render twice and I don't want it to show on the deployed app.

### CODE REVIEW

**Comment by fromITzerotoIThero** [comment]
W.,

That's the old branch what got rid of an excessive ImageCarousel from ProductPage. 
Can I ask for your review or maybe I could:
'Merge without waiting for requirements to be met (bypass branch protections)'? :)

**Comment by piotrwicijowski** [comment]
If you want to remove those components, then please remove then instead of commenting them out ;)

**Comment by fromITzerotoIThero** [comment]
Now that's a valid point! On it!

**Comment by fromITzerotoIThero** [comment]
Oh, I've just realized it might get me into some mess! It's not up-to-date with current master, so I'd have to merge master to it first... and since this issue came up again, I'll try to do it ;)

**Comment by fromITzerotoIThero** [comment]
Wow! 

(Maybe for the sake of learning I should regret it, but naaaa...) No merge conflicts! :D Carousel deleted, waiting to be reviewed.

**Review by piotrwicijowski — APPROVED** [review]
LGTM

**Comment by fromITzerotoIThero** [comment]
👍 😍

**Pull request merged**
